version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo:4.2-bionic
    ports:
      - 27017:27017
    networks:
      - node_network
  node-app:
    container_name: node-app
    image: node-app:1.0
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - node_network

networks:
  node_network:
    name: node_network